package model;


import org.apache.torque.om.Persistent;

/**
 * Tableau note
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 10 11:37:58 CET 2013]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Note
    extends model.BaseNote
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1357814278388L;

}
