package model;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * Tableau utilisateur
 *
 * This class was autogenerated by Torque on:
 *
 * [Mon Jan 21 09:42:24 CET 2013]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Utilisateur
 */
public abstract class BaseUtilisateur extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1358757744304L;

    /** The Peer class */
    private static final UtilisateurPeer peer =
        new UtilisateurPeer();


    /** The value for the id field */
    private int id;

    /** The value for the nom field */
    private String nom;

    /** The value for the prenom field */
    private String prenom;

    /** The value for the login field */
    private String login;

    /** The value for the password field */
    private String password;

    /** The value for the categorieId field */
    private int categorieId;


    /**
     * Get the Id
     *
     * @return int
     */
    public int getId()
    {
        return id;
    }


    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(int v) 
    {

        if (this.id != v)
        {
            this.id = v;
            setModified(true);
        }


    }

    /**
     * Get the Nom
     *
     * @return String
     */
    public String getNom()
    {
        return nom;
    }


    /**
     * Set the value of Nom
     *
     * @param v new value
     */
    public void setNom(String v) 
    {

        if (!ObjectUtils.equals(this.nom, v))
        {
            this.nom = v;
            setModified(true);
        }


    }

    /**
     * Get the Prenom
     *
     * @return String
     */
    public String getPrenom()
    {
        return prenom;
    }


    /**
     * Set the value of Prenom
     *
     * @param v new value
     */
    public void setPrenom(String v) 
    {

        if (!ObjectUtils.equals(this.prenom, v))
        {
            this.prenom = v;
            setModified(true);
        }


    }

    /**
     * Get the Login
     *
     * @return String
     */
    public String getLogin()
    {
        return login;
    }


    /**
     * Set the value of Login
     *
     * @param v new value
     */
    public void setLogin(String v) 
    {

        if (!ObjectUtils.equals(this.login, v))
        {
            this.login = v;
            setModified(true);
        }


    }

    /**
     * Get the Password
     *
     * @return String
     */
    public String getPassword()
    {
        return password;
    }


    /**
     * Set the value of Password
     *
     * @param v new value
     */
    public void setPassword(String v) 
    {

        if (!ObjectUtils.equals(this.password, v))
        {
            this.password = v;
            setModified(true);
        }


    }

    /**
     * Get the CategorieId
     *
     * @return int
     */
    public int getCategorieId()
    {
        return categorieId;
    }


    /**
     * Set the value of CategorieId
     *
     * @param v new value
     */
    public void setCategorieId(int v) throws TorqueException
    {

        if (this.categorieId != v)
        {
            this.categorieId = v;
            setModified(true);
        }


        if (aCategorie != null && !(aCategorie.getId() == v))
        {
            aCategorie = null;
        }

    }

    



    private Categorie aCategorie;

    /**
     * Declares an association between this object and a Categorie object
     *
     * @param v Categorie
     * @throws TorqueException
     */
    public void setCategorie(Categorie v) throws TorqueException
    {
        if (v == null)
        {
            setCategorieId( 0);
        }
        else
        {
            setCategorieId(v.getId());
        }
        aCategorie = v;
    }


    /**
     * Returns the associated Categorie object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Categorie object
     * @throws TorqueException
     */
    public Categorie getCategorie()
        throws TorqueException
    {
        if (aCategorie == null && (this.categorieId != 0))
        {
            aCategorie = CategoriePeer.retrieveByPK(SimpleKey.keyFor(this.categorieId));
        }
        return aCategorie;
    }

    /**
     * Return the associated Categorie object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Categorie object
     * @throws TorqueException
     */
    public Categorie getCategorie(Connection connection)
        throws TorqueException
    {
        if (aCategorie == null && (this.categorieId != 0))
        {
            aCategorie = CategoriePeer.retrieveByPK(SimpleKey.keyFor(this.categorieId), connection);
        }
        return aCategorie;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setCategorieKey(ObjectKey key) throws TorqueException
    {

        setCategorieId(((NumberKey) key).intValue());
    }
   
        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("Id");
            fieldNames.add("Nom");
            fieldNames.add("Prenom");
            fieldNames.add("Login");
            fieldNames.add("Password");
            fieldNames.add("CategorieId");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Id"))
        {
            return new Integer(getId());
        }
        if (name.equals("Nom"))
        {
            return getNom();
        }
        if (name.equals("Prenom"))
        {
            return getPrenom();
        }
        if (name.equals("Login"))
        {
            return getLogin();
        }
        if (name.equals("Password"))
        {
            return getPassword();
        }
        if (name.equals("CategorieId"))
        {
            return new Integer(getCategorieId());
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Id"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Nom"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setNom((String) value);
            return true;
        }
        if (name.equals("Prenom"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPrenom((String) value);
            return true;
        }
        if (name.equals("Login"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setLogin((String) value);
            return true;
        }
        if (name.equals("Password"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPassword((String) value);
            return true;
        }
        if (name.equals("CategorieId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setCategorieId(((Integer) value).intValue());
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(UtilisateurPeer.ID))
        {
            return new Integer(getId());
        }
        if (name.equals(UtilisateurPeer.NOM))
        {
            return getNom();
        }
        if (name.equals(UtilisateurPeer.PRENOM))
        {
            return getPrenom();
        }
        if (name.equals(UtilisateurPeer.LOGIN))
        {
            return getLogin();
        }
        if (name.equals(UtilisateurPeer.PASSWORD))
        {
            return getPassword();
        }
        if (name.equals(UtilisateurPeer.CATEGORIE_ID))
        {
            return new Integer(getCategorieId());
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (UtilisateurPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
      if (UtilisateurPeer.NOM.equals(name))
        {
            return setByName("Nom", value);
        }
      if (UtilisateurPeer.PRENOM.equals(name))
        {
            return setByName("Prenom", value);
        }
      if (UtilisateurPeer.LOGIN.equals(name))
        {
            return setByName("Login", value);
        }
      if (UtilisateurPeer.PASSWORD.equals(name))
        {
            return setByName("Password", value);
        }
      if (UtilisateurPeer.CATEGORIE_ID.equals(name))
        {
            return setByName("CategorieId", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getId());
        }
        if (pos == 1)
        {
            return getNom();
        }
        if (pos == 2)
        {
            return getPrenom();
        }
        if (pos == 3)
        {
            return getLogin();
        }
        if (pos == 4)
        {
            return getPassword();
        }
        if (pos == 5)
        {
            return new Integer(getCategorieId());
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("Id", value);
        }
    if (position == 1)
        {
            return setByName("Nom", value);
        }
    if (position == 2)
        {
            return setByName("Prenom", value);
        }
    if (position == 3)
        {
            return setByName("Login", value);
        }
    if (position == 4)
        {
            return setByName("Password", value);
        }
    if (position == 5)
        {
            return setByName("CategorieId", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(UtilisateurPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    UtilisateurPeer.doInsert((Utilisateur) this, con);
                    setNew(false);
                }
                else
                {
                    UtilisateurPeer.doUpdate((Utilisateur) this, con);
                }
            }

            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
        setId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
        setId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Utilisateur copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public Utilisateur copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public Utilisateur copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new Utilisateur(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public Utilisateur copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new Utilisateur(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected Utilisateur copyInto(Utilisateur copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected Utilisateur copyInto(Utilisateur copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected Utilisateur copyInto(Utilisateur copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setNom(nom);
        copyObj.setPrenom(prenom);
        copyObj.setLogin(login);
        copyObj.setPassword(password);
        copyObj.setCategorieId(categorieId);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected Utilisateur copyInto(Utilisateur copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setNom(nom);
        copyObj.setPrenom(prenom);
        copyObj.setLogin(login);
        copyObj.setPassword(password);
        copyObj.setCategorieId(categorieId);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public UtilisateurPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return UtilisateurPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Utilisateur:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("Nom = ")
           .append(getNom())
           .append("\n");
        str.append("Prenom = ")
           .append(getPrenom())
           .append("\n");
        str.append("Login = ")
           .append(getLogin())
           .append("\n");
        str.append("Password = ")
           .append(getPassword())
           .append("\n");
        str.append("CategorieId = ")
           .append(getCategorieId())
           .append("\n");
        return(str.toString());
    }
}
