package model;
import java.util.List;

import org.apache.torque.util.Criteria;


/**
 * Tableau matiere
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 10 11:37:58 CET 2013]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class MatierePeer
    extends model.BaseMatierePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1357814278388L;
    
    public static List <Matiere> doSelectAll() throws Exception {
		Criteria crit = new Criteria();
		return doSelect(crit);
	}
}
