package model;

import java.util.ArrayList;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

/**
 * Tableau note
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 10 11:37:58 CET 2013]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class NotePeer
    extends model.BaseNotePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1357814278388L;
    /**
     * Return list of Notes for a etudiantId sent
     *
     * @return List<Note>
     */
	public static List<Note> getNotesEtudiant(int etudiantId) throws TorqueException
    {
		Criteria crit = new Criteria();
		crit.add(ETUDIANT_ID, etudiantId);
    	doSelect(crit);
		
		return doSelect(crit);
    }
    
    /**
     * Return list of Notes for a etudiantId and matiereId sent
     *
     * @return List<Note>
     */
	public static List<Note> getNotesEtudiantForMatiere(int etudiantId, int matiereId) throws TorqueException
    {
		Criteria crit = new Criteria();
		crit.add(ETUDIANT_ID, etudiantId);
		
		crit.and(MATIERE_ID, matiereId);
		
		return doSelect(crit);
    }
    
    /**
     * Return list of Notes for a groupeId sent
     *
     * @return List<Note>
     */
	public static List<Note> getNotesGroupe(int groupeId) throws TorqueException
    {
		Criteria crit = new Criteria();
		crit.addJoin(EtudiantPeer.GROUPE_ID, GroupePeer.ID);
		crit.add(GroupePeer.ID, groupeId);
				
		return doSelectJoinEtudiant(crit);
    }
    
    /**
     * Return list of Notes for a groupeId and matiereId sent
     *
     * @return List<Note>
     */
	public static List<Note> getNotesGroupeForMatiere(int groupeId, int matiereId) throws TorqueException
    {
		Criteria crit = new Criteria();
		crit.add(MATIERE_ID, matiereId);
		crit.addJoin(EtudiantPeer.GROUPE_ID, GroupePeer.ID);
		crit.add(GroupePeer.ID, groupeId);
				
		return doSelectJoinEtudiant(crit);
    }
}
