package model;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.torque.util.Criteria;

/**
 * Tableau utilisateur
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 21 09:42:24 CET 2013]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UtilisateurPeer
    extends model.BaseUtilisateurPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1358757744158L;
    
    public static List<Utilisateur> doSelectAll() throws Exception {
		Criteria crit = new Criteria();
		return doSelect(crit);
	}
    
    public static boolean verifConnexion(String login, String password) throws Exception {
		List<Utilisateur> listUsers = UtilisateurPeer.doSelectAll();
		for(Utilisateur user : listUsers){
			if(user.getLogin().equals(login) && user.getPassword().equals(password))
				return true;
			System.out.println("Authentifié");
		}
		return false;
	}

}
